# Generated by Django 4.0.5 on 2022-08-24 07:43

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import ipam.fields
import taggit.managers
import ticket_firewall.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('extras', '0073_journalentry_tags_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('ticket_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='inactive', max_length=30)),
                ('id_directum', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('ticket_id',),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('index', models.PositiveIntegerField()),
                ('source_prefix', ipam.fields.IPAddressField(blank=True, default=None, null=True)),
                ('source_ports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('destination_prefix', ipam.fields.IPAddressField(blank=True, default=None, null=True)),
                ('destination_ports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('protocol', ticket_firewall.models.ChoiceArrayField(base_field=models.CharField(blank=True, max_length=4), size=None)),
                ('action', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('opened', models.DateField(blank=True, null=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ticket_firewall.ticket')),
            ],
            options={
                'ordering': ('ticket_id', 'index'),
                'unique_together': {('ticket_id', 'index')},
            },
        ),
    ]
